name = "Magglow"
uuid = "fde3be67-cf59-49cc-b7af-cfdafa7bb311"
authors = ["Yo Kusafuka <kusafuka@icrr.u-tokyo.ac.jp>"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.8.5"
Statistics = "1"
PyPlot = "2"
PyCall = "1"
JSON = "0.21"
DelimitedFiles = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
